import { StudentTypes } from '@/types';

export const studentsData: StudentTypes[] = [
  {
    key: '1',
    name: 'John Doe',
    age: 21,
    gender: 'Male',
    grade: 'A',
    address: '123 Park St, City',
  },
  {
    key: '2',
    name: 'Jane Smith',
    age: 20,
    gender: 'Female',
    grade: 'B',
    address: '456 Elm Ave, Town',
  },
  {
    key: '3',
    name: 'Mike Johnson',
    age: 22,
    gender: 'Male',
    grade: 'B+',
    address: '789 Pine Rd, Village',
  },
  {
    key: '4',
    name: 'Emily Davis',
    age: 19,
    gender: 'Female',
    grade: 'A-',
    address: '101 Maple St, City',
  },
  {
    key: '5',
    name: 'David Wilson',
    age: 23,
    gender: 'Male',
    grade: 'C+',
    address: '222 Oak Dr, Town',
  },
  {
    key: '6',
    name: 'Sophia Brown',
    age: 21,
    gender: 'Female',
    grade: 'A',
    address: '333 Birch Ave, Village',
  },
  {
    key: '7',
    name: 'Liam Martinez',
    age: 20,
    gender: 'Male',
    grade: 'B-',
    address: '444 Cedar Rd, City',
  },
  {
    key: '8',
    name: 'Olivia Taylor',
    age: 22,
    gender: 'Female',
    grade: 'A+',
    address: '555 Spruce Ln, Town',
  },
  {
    key: '9',
    name: 'Noah Anderson',
    age: 19,
    gender: 'Male',
    grade: 'B',
    address: '666 Redwood St, Village',
  },
  {
    key: '10',
    name: 'Ava Thomas',
    age: 21,
    gender: 'Female',
    grade: 'A-',
    address: '777 Palm Ave, City',
  },
  {
    key: '11',
    name: 'James White',
    age: 24,
    gender: 'Male',
    grade: 'C',
    address: '888 Pinecone Dr, Town',
  },
  {
    key: '12',
    name: 'Mia Harris',
    age: 20,
    gender: 'Female',
    grade: 'B+',
    address: '999 Aspen Rd, Village',
  },
  {
    key: '13',
    name: 'Ethan Clark',
    age: 22,
    gender: 'Male',
    grade: 'A',
    address: '1001 Cherry St, City',
  },
  {
    key: '14',
    name: 'Charlotte Lewis',
    age: 23,
    gender: 'Female',
    grade: 'A+',
    address: '1112 Walnut Ave, Town',
  },
  {
    key: '15',
    name: 'Benjamin Scott',
    age: 19,
    gender: 'Male',
    grade: 'B-',
    address: '1213 Magnolia Ln, Village',
  },
];
